# Generated by Django 3.1.5 on 2021-02-02 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_occupied', models.BooleanField(blank=True, default=True, null=True)),
                ('all_sys_in_service', models.BooleanField(blank=True, default=True, null=True)),
                ('alarm_normal', models.BooleanField(blank=True, default=True, null=True)),
                ('all_parties_notified', models.BooleanField(blank=True, default=True, null=True)),
                ('sys_remained_in_service', models.BooleanField(blank=True, default=True, null=True)),
                ('suc_dis_by_valves_open', models.BooleanField(blank=True, default=True, null=True)),
                ('guages_in_range', models.BooleanField(blank=True, default=True, null=True)),
                ('hose_valve_closed', models.BooleanField(blank=True, default=True, null=True)),
                ('valves_free_of_water', models.BooleanField(blank=True, default=True, null=True)),
                ('power_on_light', models.BooleanField(blank=True, default=True, null=True)),
                ('transfer_switch_light', models.BooleanField(blank=True, default=True, null=True)),
                ('is_olating_switch_closed', models.BooleanField(blank=True, default=True, null=True)),
                ('jockey_pump_power', models.BooleanField(blank=True, default=True, null=True)),
                ('pump_start_automatically', models.BooleanField(blank=True, default=True, null=True)),
                ('starting_pressure', models.BooleanField(blank=True, default=True, null=True)),
                ('relief_valve_working', models.IntegerField(blank=True, null=True)),
                ('suction_pressure', models.IntegerField(blank=True, null=True)),
                ('discharge_pressure', models.IntegerField(blank=True, null=True)),
                ('packing_glands_noLeaks', models.BooleanField(blank=True, default=True, null=True)),
                ('no_noise_no_vibration', models.BooleanField(blank=True, default=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('pass_inspection', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='inspection.device')),
                ('inspection_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='inspection.inspectiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
