# Generated by Django 3.1.5 on 2021-02-02 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='inspection.inspectiontype'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to=settings.AUTH_USER_MODEL),
        ),
    ]
