# Generated by Django 3.1.5 on 2021-02-05 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0002_auto_20210202_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='inspection/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
