# Generated by Django 3.1.5 on 2021-02-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_inspection_pdf_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='pdf_file',
            new_name='pdf',
        ),
    ]
