# Generated by Django 3.1.5 on 2021-02-05 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_inspectionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
