# Generated by Django 3.1.5 on 2021-02-11 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspection', '0007_inspectionreport_reported_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=50)),
                ('answer_type', models.CharField(choices=[('char_field', 'Char Field'), ('paragraph_field', 'Paragraph '), ('number_field', 'Number Field'), ('boolean_field', 'Boolean Field'), ('image_field', 'Image Field')], max_length=50)),
                ('help_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='inspection',
            old_name='user',
            new_name='inspector',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='alarm_normal',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='all_parties_notified',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='all_sys_in_service',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='building_occupied',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='discharge_pressure',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='guages_in_range',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='hose_valve_closed',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='inspection_type',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='is_olating_switch_closed',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='jockey_pump_power',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='no_noise_no_vibration',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='packing_glands_noLeaks',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='pass_inspection',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='power_on_light',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='pump_start_automatically',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='relief_valve_working',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='starting_pressure',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='suc_dis_by_valves_open',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='suction_pressure',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='sys_remained_in_service',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='transfer_switch_light',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='valves_free_of_water',
        ),
        migrations.AddField(
            model_name='device',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='inspection_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='inspection.inspectiontype'),
        ),
        migrations.AddField(
            model_name='device',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_inspector', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('ready_to_start', 'Ready to start'), ('in_progress', 'In progress'), ('complete', 'Complete')], default='ready_to_start', max_length=50),
        ),
        migrations.AddField(
            model_name='inspectiontype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_opyion_answer', to='inspection.question')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hospital', 'Hospital'), ('governace_house', 'Governance House')], default='hospital', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_entity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type_text_number', models.TextField(blank=True, null=True)),
                ('answer_type_boolean', models.BooleanField(blank=True, null=True)),
                ('answer_type_image', models.ImageField(blank=True, null=True, upload_to='inspections/question/answer/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_answer', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='inspection.question')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_question', to='inspection.question'),
        ),
    ]
