# Generated by Django 3.1.5 on 2021-02-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0010_auto_20210212_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionentity',
            name='type',
        ),
        migrations.AddField(
            model_name='inspectionentity',
            name='name',
            field=models.CharField(default='data', max_length=50),
            preserve_default=False,
        ),
    ]
