# Generated by Django 3.1.5 on 2021-02-13 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspection', '0014_auto_20210213_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_category', to=settings.AUTH_USER_MODEL),
        ),
    ]
