# Generated by Django 3.1.5 on 2021-02-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0018_auto_20210215_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='help_text',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text="The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .", null=True),
        ),
    ]
