# Generated by Django 3.1.5 on 2021-02-15 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0020_auto_20210215_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
