# Generated by Django 3.1.5 on 2021-02-16 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspection', '0022_auto_20210215_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionentity',
            name='inspectors',
            field=models.ManyToManyField(blank=True, null=True, related_name='inspection_entity_inspectors', to=settings.AUTH_USER_MODEL),
        ),
    ]
