# Generated by Django 3.1.5 on 2021-02-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0024_auto_20210216_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('ready_to_start', 'Ready to start'), ('in_progress', 'In progress'), ('complete', 'Complete')], default='ready_to_start', max_length=50),
        ),
    ]
