# Generated by Django 3.1.5 on 2021-02-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0027_auto_20210221_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionreport',
            name='inspections',
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='inspections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_report', to='inspection.inspection'),
        ),
    ]
