# Generated by Django 3.1.5 on 2021-02-23 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0028_auto_20210223_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionreport',
            old_name='inspections',
            new_name='inspection',
        ),
    ]
