# Generated by Django 3.1.5 on 2021-02-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0029_auto_20210223_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionentity',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionentity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='inspection/entity/logo/'),
        ),
    ]
